#!/usr/bin/env bash
# script to install and setup nginx
apt-get -y update
apt-get -y upgrade
apt-get install nginx -y
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
