#!/usr/bin/env bash
# This script installs a nginx web server

apt update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > sudo tee /var/www/html/index.html
sudo service nginx restart
