#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
sudo apt-get -y update
apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx.debian.html
service nginx restart
