#!/usr/bin/env bash
# Performing a 301 moved permanently redirection

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/html/index.html
strng4rep="server_name _;\n\trewrite ^\https:/\/giSirDom247 permanent;"
sudo sed -i "s/sever_name _;/$strng4rep/" /etc/ngi
