#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.

sudo apt-get update -y
sudo apt-get install -y nginx 
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement_string="server_name _;\n\t\rewrite ^\/redirect_me https:\/\/github.com\/SirDom247 permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
strn4replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$strn4replacement/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
