#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend dominicudousoro.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 206911-web-01 52.86.116.24:80
        server 206911-web-02 3.94.185.217:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
