#!/usr/bin/env bash
# server lb-01 login commands

#setting up the SSH-agent
eval $("ssh-agent")

#defining the path to IdentityFile
ssh-add ~/.ssh/school

#declaring the server username and IP Address
ssh ubuntu@18.206.207.130
